In [1]:
import pandas as pd
import json
import matplotlib.pyplot as plt 
import numpy as np
from IPython.display import HTML, Markdown, display

In [2]:
df = pd.read_csv('data/full_data.csv')

*Search for the id of the 2 teams*

In [3]:
league = "Serie_A"

df[df['league'] == league][['team_title', 'team_id']].drop_duplicates()

            team_title  team_id
428             Verona       94
435               Roma       95
442              Lazio       96
449            Bologna       97
456           Juventus       98
463            Udinese       99
470              Genoa      101
477             Napoli      105
484              Inter      106
491           Atalanta      107
498             Empoli      108
505         Fiorentina      110
512           AC Milan      111
519             Torino      113
526           Cagliari      116
533  Parma Calcio 1913      230
540              Lecce      243
547            Venezia      265
554              Monza      271
561               Como      286

In [4]:
team_1 = "Juventus"
team_2 = "Lazio"
leagues = ["Serie_A"]

In [5]:
team_1_df = df[(df['team_title'] == team_1)]
team_1_df.head()

,league,team_id,team_title,gameweek,h_a,xG,xGA,npxG,npxGA,ppda,...,loses,pts,npxGD,adv_id,adv_title,forecast_w,forecast_d,forecast_l,xG_diff,xGA_diff
456,Serie_A,98,Juventus,1,h,1.305820,0.171238,1.305820,0.171238,15.25,...,0,3,1.134582,286,Como,0.0388,0.2456,0.7156,-1.694180,0.171238
457,Serie_A,98,Juventus,2,a,1.361510,0.878611,0.600212,0.878611,12.24,...,0,3,-0.278399,94,Verona,0.1874,0.3109,0.5017,-1.638490,0.878611
458,Serie_A,98,Juventus,3,h,0.415282,0.382591,0.415282,0.382591,16.59,...,0,1,0.032691,95,Roma,0.2269,0.5223,0.2508,0.415282,0.382591
459,Serie_A,98,Juventus,4,a,0.726024,0.601249,0.726024,0.601249,13.79,...,0,1,0.124775,108,Empoli,0.2754,0.3959,0.3287,0.726024,0.601249
460,Serie_A,98,Juventus,5,h,0.419301,0.233773,0.419301,0.233773,8.91,...,0,1,0.185528,105,Napoli,0.1433,0.5664,0.2903,0.419301,0.233773

In [6]:
team_2_df = df[(df['team_title'] == team_2)]
team_2_df.head()

,league,team_id,team_title,gameweek,h_a,xG,xGA,npxG,npxGA,ppda,...,loses,pts,npxGD,adv_id,adv_title,forecast_w,forecast_d,forecast_l,xG_diff,xGA_diff
442,Serie_A,96,Lazio,1,h,2.33223,0.789649,1.57093,0.789649,5.88,...,0,3,0.781281,265,Venezia,0.0692,0.1575,0.7733,-0.66777,-0.210351
443,Serie_A,96,Lazio,2,a,1.68277,1.115810,1.68277,1.115810,6.20,...,1,0,0.566960,99,Udinese,0.2128,0.2781,0.5091,0.68277,-0.884190
444,Serie_A,96,Lazio,3,h,2.32967,1.342420,2.32967,1.342420,13.57,...,0,1,0.987250,111,AC Milan,0.1393,0.2132,0.6475,0.32967,-0.657580
445,Serie_A,96,Lazio,4,h,1.79243,0.533276,1.79243,0.533276,10.88,...,0,3,1.259154,94,Verona,0.0594,0.1917,0.7489,-0.20757,-0.466724
446,Serie_A,96,Lazio,5,a,1.14467,2.856340,1.14467,1.333740,10.73,...,1,0,-0.189070,110,Fiorentina,0.8063,0.1289,0.0648,0.14467,0.856340

In [7]:
# df[(df['team_title'] == team_1) | (df['team_title'] == team_2)].head(20)

df.columns

Index(['league', 'team_id', 'team_title', 'gameweek', 'h_a', 'xG', 'xGA',
       'npxG', 'npxGA', 'ppda', 'ppda_allowed', 'deep', 'deep_allowed',
       'scored', 'conceded', 'xpts', 'result', 'date', 'wins', 'draws',
       'loses', 'pts', 'npxGD', 'adv_id', 'adv_title', 'forecast_w',
       'forecast_d', 'forecast_l', 'xG_diff', 'xGA_diff'],
      dtype='object')

In [8]:
teams = [(team_1, team_1_df), (team_2, team_2_df)]


cols = [
    "__Points__",
    ("pts", "mean", "Points (mean)", 1),
    ("xpts", "mean", "Expected Points (mean)", 0),
    "__Attacking__",
    ("xG", "mean", "Expected goals (mean)", 1),
    ("ppda_allowed", "mean", "PPDA allowed (mean)", 1),
    ("npxG", "mean", "Non-penalty xG (mean)", 1),
    ("deep", "mean", "Deep passes (mean)", 1),
    "__Scoring__",
    ("scored", "mean", "Goals scored (mean)", 1),
    # ("scored", "sum", "Goals scored (sum)", 1),
    ("xG_diff", "mean", "xG diff (mean)", 1),
    "__Defending__",
    ("ppda", "mean", "PPDA (mean)", -1),
    ("xGA", "mean", "xG allowed (mean)", -1),
    ("conceded", "mean", "Goals conceded (mean)", -1),
    ("npxGA", "mean", "Non-penalty xG allowed (mean)", -1),
    ("deep_allowed", "mean", "Deep passes allowed (mean)", - 1),
    "__Other__",
    ("deep", "sum", "Deep passes (sum)", 1),
    ("deep_allowed", "sum", "Deep passes allowed (sum)", - 1),
    ("npxGD", "mean", "Non-penalty xG diff (mean)", -1),
    ("xGA_diff", "sum", "xG allowed diff (sum)", 1),
]


table = "<table>"
table += f"<tr><td></td><th>{team_1}</th><th>{team_2}</th></tr>"
for col in cols:
    if type(col) == str:
        table += f"<tr><td colspan='3' style='text-align: center;'>{col.replace('__', ' ---------- ')}</td></tr>"
        continue

    c, fn, title, best = col
    if fn == "mean":
        v1 = team_1_df[c].mean()
        v2 = team_2_df[c].mean()
    elif fn == "sum":
        v1 = team_1_df[c].sum()
        v2 = team_2_df[c].sum()

    c1 = ""
    c2 = ""
    if best == 1:
        if v1 > v2:
            c1 = "green"
        elif v1 < v2:
            c2 = "green"
    elif best == -1:
        if v1 < v2:
            c1 = "green"
        elif v1 > v2:
            c2 = "green"

    table += f"<tr><td style='text-align: left;'>{title}</td><td style='color:{c1}'>{v1.round(decimals=2)}</td><td style='color:{c2}'>{v2.round(decimals=2)}</td></tr>"
    
table += "</table>"
display(HTML(table))

In [9]:
t_col = ['team_title', 'league']
cols = [*t_col, 'xG', 'xGA', 'npxG', 'npxGA', 'ppda', 'ppda_allowed', 'deep', 'deep_allowed', 'scored', 'conceded', 'pts', 'npxGD', 'xGA_diff', 'xG_diff']


m_df = df[cols].groupby(['team_title', 'league']).mean() 
m_df.reset_index(inplace=True)  

# m_df.head()

In [16]:
short = True

cols = [('xG', False), ('xGA', True), ('ppda', True), ('ppda_allowed', False), ('deep', False), ('deep_allowed', True), ('scored', False), ('conceded', True), ('pts', False), ('npxGD', False), ('xGA_diff', False), ('xG_diff', False)]
teams = [team_1, team_2]
table = ""
for c, asc in cols:
    for league in leagues:
        table += f"<div style='margin:10px'><h3>{c} {league}</h3><table>"
        vals = m_df[m_df['league'] == league].sort_values(c, ascending=asc)[['team_title', c]].values

        for i, (team, xG) in enumerate(vals):
            color = ""
            if team in teams:
                if short:
                    table += f"<tr style='color:{color}'><td>{i+1}</td><td>{team}</td><td>{xG}</td></tr>"
                else:
                    color = "green"
            if not short:
                table += f"<tr style='color:{color}'><td>{i+1}</td><td>{team}</td><td>{xG}</td></tr>"
        table += "</table></div>"

display(HTML("<div style='display:flex; flex-direction:row;flex-wrap: wrap;'>"+table+"</div>"))

In [45]:
df_players = pd.read_csv('data/full_data_players.csv')

df_teams_players = df_players[(df_players['team_title'] == team_1) | (df_players['team_title'] == team_2)]

In [46]:
df_teams_players.head()

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,...,league,xG_diff,npxG_diff,assists_diff,npxG_per_shot,npg90,npxG90,xG90,xA90,p_scored
1282,7084,Dusan Vlahovic,7,582,5,6.251922,0,0.470296,26,3,...,Serie_A,1.251922,1.968025,0.470296,0.240459,0.309278,0.613612,0.966792,0.072726,3
1287,7224,Boulaye Dia,6,424,3,1.690049,0,0.823159,9,5,...,Serie_A,-1.309951,-1.309951,0.823159,0.187783,0.636792,0.358737,0.358737,0.174727,0
1292,10948,Valentín Castellanos,6,515,3,4.891445,1,1.042130,25,5,...,Serie_A,1.891445,1.130146,0.042130,0.195658,0.524272,0.721773,0.854816,0.182120,0
1300,1958,Mattia Zaccagni,7,617,2,2.483234,2,1.199569,15,15,...,Serie_A,0.483234,0.721935,-0.800431,0.165549,0.145867,0.251174,0.362222,0.174978,1
1320,687,Pedro,3,36,1,0.121540,0,0.025529,2,1,...,Serie_A,-0.878460,-0.878460,0.025529,0.060770,2.500000,0.303851,0.303851,0.063823,0

In [65]:
def best_scorers_team(team, df_teams_players, n=5):
    return df_teams_players[df_teams_players['team_title'] == team].sort_values('npg', ascending=False)[['player_name', 'position', 'time', 'xG', 'goals', 'npg','p_scored','xG_diff']].head(n)

def best_xg90(df_teams_players, n=10):
    return df_teams_players[df_teams_players['time'] >= 90].sort_values('xG90', ascending=False)[['player_name', 'team_title','position', 'time', 'xG90', 'goals', 'npg','p_scored','xG_diff']].head(n)

In [66]:
best_xg90(df_teams_players)

,player_name,team_title,position,time,xG90,goals,npg,p_scored,xG_diff
1282,Dusan Vlahovic,Juventus,F,582,0.966792,5,2,3,1.251922
1292,Valentín Castellanos,Lazio,F,515,0.854816,3,3,0,1.891445
1300,Mattia Zaccagni,Lazio,F M,617,0.362222,2,1,1,0.483234
1287,Boulaye Dia,Lazio,F M S,424,0.358737,3,3,0,-1.309951
1628,Teun Koopmeiners,Juventus,M S,360,0.297661,0,0,0,1.190646
1384,Tijjani Noslin,Lazio,F M S,239,0.266668,1,1,0,-0.291849
1393,Francisco Conceição,Juventus,M S,159,0.262092,1,1,0,-0.536971
1629,Loum Tchaouna,Lazio,M S,134,0.261055,0,0,0,0.388682
1375,Gustav Isaksen,Lazio,M S,351,0.202957,1,1,0,-0.208466
1536,Kephren Thuram,Juventus,M S,178,0.185335,0,0,0,0.366552

In [60]:
best_scorers_team(team_1, df_teams_players)

,player_name,position,time,xG,goals,npg,p_scored,xG_diff
1282,Dusan Vlahovic,F,582,6.251922,5,2,3,1.251922
1363,Andrea Cambiaso,D M S,552,0.158742,1,1,0,-0.841258
1389,Samuel Mbangula,M S,310,0.103225,1,1,0,-0.896775
1390,Nicolò Savona,D S,387,0.493706,1,1,0,-0.506294
1393,Francisco Conceição,M S,159,0.463029,1,1,0,-0.536971

In [61]:
best_scorers_team(team_2, df_teams_players)

,player_name,position,time,xG,goals,npg,p_scored,xG_diff
1287,Boulaye Dia,F M S,424,1.690049,3,3,0,-1.309951
1292,Valentín Castellanos,F,515,4.891445,3,3,0,1.891445
1300,Mattia Zaccagni,F M,617,2.483234,2,1,1,0.483234
1320,Pedro,S,36,0.121540,1,1,0,-0.878460
1342,Matteo Guendouzi,M,629,0.242075,1,1,0,-0.757925

In [25]:
# table_content = []

# for ic, c in enumerate(cols[2:]):
#     row = []
#     for team, team_df in teams:
#         for i, pct in enumerate(pctls_by_col_x[ic]):
#             if team_df[c].mean() > pct and team_df[c].mean() < pctls_by_col[c].max():
#                 continue
#             row.append([team, c, i])
#             break
#     table_content.append(row)


# table = "<table>"
# table += f"<tr><td></td><th>{team_1}</th><th>{team_2}</th></tr>"
# for ab in table_content:
#     _, c, i = ab[0]
#     _, _, j = ab[1]
#     table += f"<tr><td style='text-align: left;'>{c}</td><td>{(i+1)*10}th</td><td>{(j+1)*10}th</td></tr>"
# table += "</table>"
# display(HTML(table))